# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
      
      - name: Use specific Java version for sdkmanager
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Download Android Emulator Image
        run: |
          echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "system-images;android-27;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd -n emu -k "system-images;android-27;google_apis;x86" -b "x86" -c 1G -d 7 -f
      
      - name: Android test
        timeout-minutes: 5
        continue-on-error: true
        run: |
          mkdir -p artifacts
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          $ANDROID_HOME/emulator/emulator @emu &
          adb wait-for-device; adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'; adb shell wm dismiss-keyguard
          npm run e2e

